package `fun`.walawe.constant

const val BASE_URL_CALL = BuildConfig.BASE_URL
const val DEFAULT_MODEL_DOWNLOADER_URI = BuildConfig.BASE_URL.plus(BuildConfig.FILENAME_MINICPM_V2_Q4_KM)

const val MODEL_FILENAME_QWEN = BuildConfig.MODEL_FILENAME_QWEN
const val MODEL_FILENAME_PALIGEMMA = BuildConfig.MODEL_FILENAME_PALIGEMMA
const val MODEL_FILENAME_MINICPM = BuildConfig.MODEL_FILENAME_MINICPM

const val BASENAME_QWEN3_VL_MODEL = BuildConfig.BASENAME_QWEN3_VL_MODEL
const val BASENAME_MINICPM_V2_MODEL = BuildConfig.BASENAME_MINICPM_V2_MODEL

const val DEFAULT_HARDWARE_ACCELERATOR = 0
const val DEFAULT_DEVELOPER_MODE = false
const val DEFAULT_IS_MODEL_DOWNLOADED = false
const val DEFAULT_LAST_MODEL_SYNC_TIME = 0L
const val DEFAULT_LAST_MODEL_PATH = ""
const val DEFAULT_LAST_MODEL_FILENAME = ""
