package `fun`.walawe.constant

const val MODEL_FILENAME_MINICPM_LLM = BuildConfig.MODEL_FILENAME_MINICPM
const val MODEL_DISPLAYNAME_MINICPM_LLM = "MiniCPM-V4.6.gguf"

const val MODEL_FILENAME_MINICPM_MMPROJ = BuildConfig.MODEL_FILENAME_MINICPM_MMPROJ
const val MODEL_DISPLAYNAME_MINICPM_MMPROJ = "MiniCPM-Mmproj.gguf"

const val MODEL_FILENAME_EMBEDDING = BuildConfig.MODEL_FILENAME_EMBEDDING
const val MODEL_DISPLAYNAME_EMBEDDING = "EmbeddingGemma-300m.gguf"

const val DEFAULT_MODEL_SYSTEM_PROMPT = BuildConfig.DEFAULT_SYSTEM_PROMPT

const val MODEL_FILENAME_OPENNLP_SENTENCE="opennlp-en-ud-ewt-sentence-1.3-2.5.4.bin"
const val DEFAULT_FILENAME_FAISS_PERSISTANCE="chunk_vector.faiss"

const val KEENABLE_API_KEY = BuildConfig.MCP_KEENABLE_API_KEY
const val HUGGINGFACE_API_KEY = BuildConfig.HUGGINGFACE_API_KEY

const val FIREBASE_ANALYTICS_KEY_FETCH_ERROR = "remote_config_fetch_error"
