package `fun`.walawe.constant

const val BASE_URL_CALL = BuildConfig.BASE_URL

const val MODEL_FILENAME_MINICPM = BuildConfig.MODEL_FILENAME_MINICPM
const val MODEL_FILENAME_MINICPM_MMPROJ = BuildConfig.MODEL_FILENAME_MINICPM_MMPROJ
const val MODEL_FILENAME_EMBEDDING = BuildConfig.MODEL_FILENAME_EMBEDDING
const val DEFAULT_MODEL_SYSTEM_PROMPT = BuildConfig.DEFAULT_SYSTEM_PROMPT

// OpenNLP Sentence and Tokenize ONNX model filename
const val MODEL_FILENAME_OPENNLP_SENTENCE="opennlp-en-ud-ewt-sentence-1.3-2.5.4.bin"
const val MODEL_FILENAME_OPENNLP_TOKEN="opennlp-en-ud-ewt-tokens-1.3-2.5.4.bin"

const val DEFAULT_MODEL_DOWNLOADER_URI = BASE_URL_CALL.plus(MODEL_FILENAME_MINICPM)
const val DEFAULT_MMPROJ_DOWNLOADER_URI = BASE_URL_CALL.plus(MODEL_FILENAME_MINICPM_MMPROJ)
const val DEFAULT_EMBEDDING_DOWNLOADER_URI = BASE_URL_CALL.plus(MODEL_FILENAME_EMBEDDING)
